version = 0.1

[default.build.parameters]
profile = "null-application-profile"
template_file = "template-dev.yaml"

[default.deploy.parameters]
stack_name = "accelerate-mx-api-dev"
profile = "null-application-profile"
resolve_s3 = true
region = "us-east-1"
capabilities = "CAPABILITY_IAM CAPABILITY_NAMED_IAM CAPABILITY_AUTO_EXPAND"
image_repositories = []

