export default async function (prisma, customerId) {
   console.log('Seeding products...');

   // define products in overall product catalog
   const products = [
      {
         id: 'cm7km80iv000008l82nzu3ipn',
         name: 'Hydraulic Pump Assembly',
         description: 'Primary hydraulic pump for commercial aircraft',
         part_number: 'HYD-PMP-1001',
         manufacturer: 'Parker Aerospace',
         model: 'HP1001',
         quantity_in_stock: 15,
         reorder_threshold: 5,
         category: 'Aircraft Components',
         sub_category: 'Hydraulic Systems',
         unit_price: 3200.0,
         deleted: false,
      },
      {
         id: 'cm7km86rr000108l8ct6adys3',
         name: 'Fuel Flow Transmitter',
         description:
            'Measures fuel flow rate for engine efficiency monitoring',
         part_number: 'FFX-2005',
         manufacturer: 'Honeywell Aerospace',
         model: 'FFX2005',
         quantity_in_stock: 10,
         reorder_threshold: 3,
         category: 'Aircraft Components',
         sub_category: 'Fuel Systems',
         unit_price: 2750.0,
         deleted: false,
      },
      {
         id: 'cm7km8bta000208l8fqyvgmlz',
         name: 'Avionics Cooling Fan',
         description: 'Provides ventilation for avionics bay cooling',
         part_number: 'AVF-7503',
         manufacturer: 'Collins Aerospace',
         model: 'AV7503',
         quantity_in_stock: 25,
         reorder_threshold: 10,
         category: 'Aircraft Components',
         sub_category: 'Electrical & Avionics',
         unit_price: 870.0,
         deleted: false,
      },
      {
         id: 'cm7km8gui000308l8997z46mt',
         name: 'Boeing 737 Engine Stand',
         description: 'Used for maintenance and storage of Boeing 737 engines',
         part_number: 'ENG-STND-737',
         manufacturer: 'Tronair',
         model: '737-ENG',
         quantity_in_stock: 5,
         reorder_threshold: 1,
         category: 'Maintenance Equipment',
         sub_category: 'Engine Handling',
         unit_price: 15000.0,
         deleted: false,
      },
      {
         id: 'cm7km8qrt000508l8625zg9ir',
         name: 'Torque Wrench (Digital)',
         description:
            'Precision digital torque wrench for aircraft maintenance',
         part_number: 'TW-DIG-500',
         manufacturer: 'Snap-on Tools',
         model: 'TW500D',
         quantity_in_stock: 30,
         reorder_threshold: 10,
         category: 'Maintenance Equipment',
         sub_category: 'Tools',
         unit_price: 450.0,
         deleted: false,
      },
      {
         id: 'cm7km8m0q000408l84xcihevj',
         name: 'Titanium Hex Bolts (Set of 10)',
         description:
            'Corrosion-resistant titanium bolts for aerospace applications',
         part_number: 'THB-0010',
         manufacturer: 'Alcoa Fasteners',
         model: 'THB10',
         quantity_in_stock: 100,
         reorder_threshold: 20,
         category: 'Fasteners & Hardware',
         sub_category: 'Bolts',
         unit_price: 120.0,
         deleted: false,
      },
      {
         id: 'cm7km8v34000608l8b2zub9v8',
         name: 'Locking Nut - High Temp',
         description:
            'High-temperature resistant locking nut for turbine applications',
         part_number: 'LNT-HT-330',
         manufacturer: 'Safran',
         model: 'LNT330',
         quantity_in_stock: 250,
         reorder_threshold: 50,
         category: 'Fasteners & Hardware',
         sub_category: 'Nuts',
         unit_price: 15.0,
         deleted: false,
      },
      {
         id: 'cm7km8zd6000708l85v3y73wx',
         name: 'Brake Disc Assembly',
         description: 'High-performance carbon composite brake disc',
         part_number: 'BDA-500X',
         manufacturer: 'Goodrich',
         model: 'BDA500X',
         quantity_in_stock: 8,
         reorder_threshold: 2,
         category: 'Landing Gear Components',
         sub_category: 'Braking Systems',
         unit_price: 4500.0,
         deleted: false,
      },
      {
         id: 'cm7km940h000808l86acc8czs',
         name: 'Shock Absorber Strut',
         description: 'Hydraulic strut for main landing gear',
         part_number: 'SAS-MG-320',
         manufacturer: 'Messier-Bugatti-Dowty',
         model: 'SAS320',
         quantity_in_stock: 12,
         reorder_threshold: 4,
         category: 'Landing Gear Components',
         sub_category: 'Shock Absorbers',
         unit_price: 3800.0,
         deleted: false,
      },
      {
         id: 'cm7km99um000908l8dvdjc1ww',
         name: 'Ni-Cad Aircraft Battery',
         description: '24V Nickel-Cadmium battery for avionics backup power',
         part_number: 'NCB-24V-400',
         manufacturer: 'Saft Batteries',
         model: 'NCB400',
         quantity_in_stock: 20,
         reorder_threshold: 5,
         category: 'Electrical Systems',
         sub_category: 'Batteries',
         unit_price: 920.0,
         deleted: false,
      },
      {
         id: 'cm7km9ec4000a08l829wjasi0',
         name: 'LED Taxi Light',
         description:
            'High-intensity LED taxi light for improved runway visibility',
         part_number: 'TXL-LED-100',
         manufacturer: 'Whelen Aerospace Technologies',
         model: 'TXL100',
         quantity_in_stock: 40,
         reorder_threshold: 15,
         category: 'Electrical Systems',
         sub_category: 'Lighting',
         unit_price: 275.0,
         deleted: false,
      },
   ];

   for (const product of products) {
      // upsert in db
      await prisma.product.upsert({
         where: { id: product.id },
         update: {},
         create: product,
      });

      // create mapping to customer
      await prisma.customerToProductMap.upsert({
         where: {
            customer_id_product_id: {
               customer_id: customerId,
               product_id: product.id,
            },
         },
         update: {},
         create: {
            customer_id: customerId,
            product_id: product.id,
         },
      });
   }
}
